version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./api   
      dockerfile: Dockerfile   
    container_name: api
    depends_on:
      - mongodb
    ports:
      - "5050:5000" 
    env_file:
      - .env        
   
volumes:
  mongo_data:

