version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web-app:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: web-app
    depends_on:
      - mongodb
    ports:
      - "5050:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - .:/app 

volumes:
  mongo_data:

