name: finallapis2
services:
  - name: api
    image:
      registry_type: DOCKER_HUB
      registry: ziruihan
      repository: api
      tag: latest
    http_port: 5000
    routes:
      - path: /
    envs:
      - key: FLASK_SECRET_KEY
        value: somerandomlongsecret123
      - key: MONGO_URI
        value: mongodb://mongodb:27017/consent_data
    instance_size_slug: basic-xxs
    instance_count: 1
