name: API CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd api
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          cd api
          pytest --cov=. tests/

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          cd api
          docker build -t ziruihan/api:latest .

      - name: Push Docker Image
        run: |
          docker push ziruihan/api:latest

      - name: Wait for DockerHub to sync
        run: |
          echo "Waiting 30 seconds for DockerHub to sync image..."
          sleep 30

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
           token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Validate Spec
        run: |
           doctl apps spec validate api/do-app-spec.yaml

      - name: Update App Platform App
        run: |
            doctl apps update ${{ secrets.DO_APP_ID }} --spec api/do-app-spec.yaml


